### ISSUE TITLE
Develop a Singlecarrier PHY Layer

### ISSUE THREAD

**Issue by lukasostendorf** [HAMNET-Access-Protocol/HNAP4PlutoSDR#25]
The given channel bandwidth of 200 kHz is somewhat of an edge-case in terms of frequency selectiveness. Lower channel bandwidths will undergo flat fading, higher bandwidths will undergo frequency selective fading. 

For a flat fading scenario, a singlecarrier solution would also be easy to implement and will make it easier to find a PA which amplifies the signal (due to lower PAPR). In case of high frequency selectiveness, the OFDM PHY layer is expected to be more robust but requires a very linear PA.

In order to compare both approaches, we will develop a singlecarrier version of the PHY layer which is compatible to the existing MAC layer.

## Tasks
- [x] definition of the SC PHY layer
- [x] general single carrier modulation functions
- [x] new timing synchronization sequence and correlation algorithm
- [x] include pulse shaping
- [x] include training sequences and a LMS equalizer
- [ ] integrate SC phy to current develop branch

## SC PHY Definition

- 300 kSymb/s sampling rate
- RRC filter for pulse shaping, with factor 2 interpolation/decimation -> 150 kSymb/s baseband sampling rate
- LMS Equalizer with 8 (?) taps
- Every data slot will contain 40 training symbols at the beginning of the slot followed by 520 data symbols
- Synchronization sequence is a 119 symbol Zadoff Chu sequence
- Zadoff chu is also used in uplink for initial sync.

**Comment by kantooon** [comment]
Hi @lukasostendorf I watched your SDRA talk and think that depending on how much bandwith you are willing to sacrifice, you might use FSK instead of PSK to be able to work with class C amplifiers. I recently implemented a 4FSK (RRC and 1/2 rate convolutional code) modem in qradiolink and am quite satisfied with RF performance on a regular FM amplifier.

**Comment by DG9BFC** [comment]
hmmm single carrier ?? why not also add slower packet speeds?? on pluto you sure can transmit also in 1k2 2k4 4k8 9k6 and higher ... one unit fits all ... slow speed packet ... high speed packet ... hamnet ... whatevernet

**Comment by dranch** [comment]
Will this enhancement be able to lower HNAP's consumed bandwidth to 100Khz and lower the symbol rate to 56KSymbols/sec?  This would be great to have to meet the USA's FCC requirements.  Here is some back ground of the ARRL trying to get these limitations changed but it's been 5yrs with no movement: https://www.federalregister.gov/documents/2016/08/12/2016-19085/amateur-radio-service-rules-to-permit-greater-flexibility-in-data-communications )
